# This workflow ensures markdown files follow our style guide
# Logic:
# 1. Runs on default branch only (pushes and PRs targeting it)
# 2. Uses our local npm scripts for consistency
# 3. Attempts to auto-fix issues and commits them on PRs
# 4. Runs all markdown-related checks (lint, spell-check)

name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  check-and-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Run format check first since it's quick
      - name: Check Formatting
        run: pnpm run format:check

      # Run markdown fixes and checks
      - name: Check Markdown Format
        run: pnpm run fix:md
